# GitHub Actions workflow for automatic backend deployment
name: Backend Auto-Deploy

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - 'requirements*.txt'
      - 'Dockerfile*'
      - 'docker-compose*.yml'
      - '.env*'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'requirements*.txt'
      - 'Dockerfile*'
      - 'docker-compose*.yml'

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        pytest test_backend.py -v --cov=.
    
    - name: Build Docker image
      run: |
        docker build -f Dockerfile.dev -t visitor-backend:test .
    
    - name: Test Docker deployment
      run: |
        docker-compose -f docker-compose.dev.yml up -d --build
        sleep 30
        curl -f http://localhost:8000/health || exit 1
        docker-compose -f docker-compose.dev.yml down
    
    - name: Deploy to development (if main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚀 Deployment would happen here"
        # Add actual deployment commands for your environment
        # ./scripts/auto-deploy.sh